{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "432161a1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🔍 [AI 투자 대시보드] 분석 시작...\n",
      "📊 전체 시장 분위기(과열 및 주의) 분석 중...\n",
      "📂 테마별 주요 종목 전수 조사 중...\n",
      "✅ 삼성전자 분석 완료\n",
      "✅ SK하이닉스 분석 완료\n",
      "✅ 한미반도체 분석 완료\n",
      "✅ DB하이텍 분석 완료\n",
      "✅ LG에너지솔루션 분석 완료\n",
      "✅ 삼성SDI 분석 완료\n",
      "✅ 현대차 분석 완료\n",
      "✅ 기아 분석 완료\n",
      "✅ 현대모비스 분석 완료\n",
      "✅ 한온시스템 분석 완료\n",
      "✅ 대한전선 분석 완료\n",
      "✅ LS 분석 완료\n",
      "✅ 효성중공업 분석 완료\n",
      "✅ HD현대일렉트릭 분석 완료\n",
      "✅ 삼성바이오로직스 분석 완료\n",
      "✅ 셀트리온 분석 완료\n",
      "\n",
      "============================================================\n",
      "📢 [시장 심리 진단]: 🔥 매우 과열 (과열 주의)\n",
      "============================================================\n",
      "\n",
      "🔥 [지금 돈이 몰리는 테마 순위]\n",
      "1위: 전력/구리 (점수: 3.5) - ↗️ 강세\n",
      "2위: 이차전지 (점수: 1.0) - ➡️ 보합\n",
      "3위: 반도체 (점수: 0.0) - ➡️ 보합\n",
      "4위: 자동차 (점수: 0.0) - ➡️ 보합\n",
      "5위: 바이오 (점수: 0.0) - ➡️ 보합\n",
      "\n",
      "🚀 [내일이 기대되는 테마별 대장주 TOP 5]\n",
      "- 대한전선(전력/구리): 예상 수익 +1.84%\n",
      "- LS(전력/구리): 예상 수익 +1.11%\n",
      "- DB하이텍(반도체): 예상 수익 +0.88%\n",
      "- HD현대일렉트릭(전력/구리): 예상 수익 +0.79%\n",
      "- 삼성SDI(이차전지): 예상 수익 +0.53%\n",
      "\n",
      "✅ 리포트가 바탕화면에 저장되었습니다.\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "import pandas as pd\n",
    "import FinanceDataReader as fdr\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import time\n",
    "from datetime import datetime, timedelta\n",
    "import os\n",
    "\n",
    "# 1. 테마 정의 (민성님이 언제든 수정 가능)\n",
    "THEMES = {\n",
    "    '반도체': ['삼성전자', 'SK하이닉스', '한미반도체', 'DB하이텍', '리노공업'],\n",
    "    '이차전지': ['에코프로', '에코프로비엠', 'LG에너지솔루션', '포스코홀딩스', '삼성SDI'],\n",
    "    '자동차': ['현대차', '기아', '현대모비스', '한온시스템'],\n",
    "    '전력/구리': ['대한전선', 'LS', 'LS Electric', '효성중공업', 'HD현대일렉트릭'],\n",
    "    '바이오': ['삼성바이오로직스', '셀트리온', '알테오젠', 'HLB']\n",
    "}\n",
    "\n",
    "def get_weekly_sentiment(name):\n",
    "    \"\"\"최근 7일 뉴스 종합 분석\"\"\"\n",
    "    end_date = datetime.now()\n",
    "    start_date = end_date - timedelta(days=7)\n",
    "    query = f\"{name} after:{start_date.strftime('%Y-%m-%d')}\"\n",
    "    url = f\"https://news.google.com/rss/search?q={query}&hl=ko&gl=KR&ceid=KR:ko\"\n",
    "    score = 0\n",
    "    try:\n",
    "        res = requests.get(url, timeout=7)\n",
    "        soup = BeautifulSoup(res.content, 'xml')\n",
    "        items = soup.find_all('item')\n",
    "        pos_words = ['상승', '호재', '매수', '돌파', '성장', '흑자', '수주', '긍정']\n",
    "        neg_words = ['하락', '악재', '매도', '급락', '우려', '손실', '적자', '부정']\n",
    "        for item in items[:10]:\n",
    "            text = item.title.text\n",
    "            for pw in pos_words: \n",
    "                if pw in text: score += 0.5\n",
    "            for nw in neg_words: \n",
    "                if nw in text: score -= 0.5\n",
    "    except: pass\n",
    "    return score\n",
    "\n",
    "def analyze_market():\n",
    "    \"\"\"옵션 2: 시장 과열 지수 계산\"\"\"\n",
    "    print(\"📊 전체 시장 분위기(과열 및 주의) 분석 중...\")\n",
    "    kospi = fdr.DataReader('KS11', (datetime.now() - timedelta(days=20)).strftime('%Y-%m-%d'))\n",
    "    # 최근 변동성 및 RSI 등을 활용한 심리 지수 (간략화)\n",
    "    recent_change = ((kospi['Close'].iloc[-1] / kospi['Close'].iloc[-5]) - 1) * 100\n",
    "    if recent_change > 2: status = \"🔥 매우 과열 (과열 주의)\"\n",
    "    elif recent_change > 0: status = \"⚖️ 과열 (매수세 우위)\"\n",
    "    elif recent_change > -2: status = \"😨 주의 (조심스러운 접근)\"\n",
    "    else: status = \"💀 매우 주의 (바닥 확인 필요)\"\n",
    "    return status\n",
    "\n",
    "# 2. 메인 분석 실행\n",
    "print(f\"🔍 [AI 투자 대시보드] 분석 시작...\")\n",
    "market_status = analyze_market()\n",
    "\n",
    "# 테마별 점수 합산을 위한 변수\n",
    "theme_scores = {theme: 0 for theme in THEMES}\n",
    "stock_results = []\n",
    "\n",
    "print(\"📂 테마별 주요 종목 전수 조사 중...\")\n",
    "for theme, stocks in THEMES.items():\n",
    "    for name in stocks:\n",
    "        # 티커(코드) 찾기 (이름으로 찾기 기능 활용)\n",
    "        try:\n",
    "            df_list = fdr.StockListing('KOSPI')\n",
    "            code = df_list[df_list['Name'] == name]['Code'].values[0]\n",
    "            \n",
    "            # 주가 및 뉴스 분석\n",
    "            df = fdr.DataReader(code, (datetime.now() - timedelta(days=20)).strftime('%Y-%m-%d'))\n",
    "            curr_price = float(df['Close'].iloc[-1])\n",
    "            daily_vol = df['Close'].pct_change().std() * 100 \n",
    "            \n",
    "            score = get_weekly_sentiment(name)\n",
    "            theme_scores[theme] += score # 테마 점수 누적\n",
    "            \n",
    "            expected_return = daily_vol * (score * 0.2)\n",
    "            \n",
    "            stock_results.append({\n",
    "                '테마': theme,\n",
    "                '종목명': name,\n",
    "                '현재가': int(curr_price),\n",
    "                '뉴스점수': score,\n",
    "                '예상수익률': expected_return\n",
    "            })\n",
    "            print(f\"✅ {name} 분석 완료\")\n",
    "        except: continue\n",
    "        time.sleep(0.1)\n",
    "\n",
    "# 3. 데이터 가공\n",
    "final_df = pd.DataFrame(stock_results)\n",
    "\n",
    "# 옵션 3: 테마별 순위 매기기\n",
    "theme_ranking = pd.Series(theme_scores).sort_values(ascending=False)\n",
    "\n",
    "# 4. 최종 리포트 출력\n",
    "print(\"\\n\" + \"=\"*60)\n",
    "print(f\"📢 [시장 심리 진단]: {market_status}\")\n",
    "print(\"=\"*60)\n",
    "\n",
    "print(\"\\n🔥 [지금 돈이 몰리는 테마 순위]\")\n",
    "for i, (theme, score) in enumerate(theme_ranking.items()):\n",
    "    status = \"↗️ 강세\" if score > 2 else \"➡️ 보합\" if score >= 0 else \"↘️ 약세\"\n",
    "    print(f\"{i+1}위: {theme} (점수: {score:.1f}) - {status}\")\n",
    "\n",
    "print(\"\\n🚀 [내일이 기대되는 테마별 대장주 TOP 5]\")\n",
    "top_stocks = final_df.sort_values(by='예상수익률', ascending=False).head(5)\n",
    "for i, row in top_stocks.iterrows():\n",
    "    print(f\"- {row['종목명']}({row['테마']}): 예상 수익 {row['예상수익률']:+.2f}%\")\n",
    "\n",
    "# 5. 저장\n",
    "desktop = os.path.join(os.path.expanduser('~'), 'Desktop', 'AI_테마_분석_리포트.xlsx')\n",
    "final_df.to_excel(desktop, index=False)\n",
    "print(f\"\\n✅ 리포트가 바탕화면에 저장되었습니다.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
