name: Stock AI Predictor

on:
  workflow_dispatch:      # 구글 앱스 스크립트용
  repository_dispatch:    # 텔레그램 버튼(/start)용
    types: [telegram_start]
  schedule:
    - cron: '30 23 * * *' # 백업용 아침 8시 30분

jobs:
  build:
    # 텔레그램 버튼을 눌렀을 때(repository_dispatch)나 
    # 구글/수동으로 실행했을 때(workflow_dispatch, schedule) 모두 실행되게 설정
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' || github.event_name == 'schedule'
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pandas_datareader yfinance scikit-learn matplotlib requests python-telegram-bot

      - name: Run Stock Prediction
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python stock_predict.py
